// Auto-generated by codegen — DO NOT EDIT. Run: bun run db:codegen
import type { Context } from "../system.ts";

export type Sessions = {
  id: string;
  user_id: string;
  created_at: Date;
  expires_at: Date;
};

type Defaults = "id" | "created_at" | "expires_at";
export type SessionsCreate = Omit<Sessions, Defaults> & Partial<Pick<Sessions, Defaults>>;
export type SessionsUpdate = Partial<Omit<Sessions, "id">>;

export async function create(ctx: Context, data: SessionsCreate): Promise<Sessions> {
  const [row] = await ctx.sql`INSERT INTO public.sessions ${ctx.sql(data)} RETURNING *`;
  return row as Sessions;
}

export async function read(ctx: Context, id: string): Promise<Sessions | null> {
  const rows = await ctx.sql`SELECT * FROM public.sessions WHERE id = ${id}`;
  return (rows[0] as Sessions) ?? null;
}

export async function update(ctx: Context, id: string, data: SessionsUpdate): Promise<Sessions | null> {
  const rows = await ctx.sql`UPDATE public.sessions SET ${ctx.sql(data)} WHERE id = ${id} RETURNING *`;
  return (rows[0] as Sessions) ?? null;
}

export async function remove(ctx: Context, id: string): Promise<boolean> {
  const rows = await ctx.sql`DELETE FROM public.sessions WHERE id = ${id} RETURNING id`;
  return rows.length > 0;
}

export async function list(ctx: Context, opts: { limit?: number; offset?: number } = {}): Promise<Sessions[]> {
  const { limit = 100, offset = 0 } = opts;
  return await ctx.sql`SELECT * FROM public.sessions ORDER BY id LIMIT ${limit} OFFSET ${offset}` as Sessions[];
}
