// Auto-generated by codegen — DO NOT EDIT. Run: bun run db:codegen
import type { Context } from "../system.ts";
import { prepareForSql } from "../lib/db.ts";

export type TypeTest = {
  id: string;
  col_smallint?: number;
  col_integer?: number;
  col_bigint?: string;
  col_serial: number;
  col_real?: number;
  col_double?: number;
  col_numeric?: string;
  col_money?: string;
  col_bool: boolean;
  col_text: string;
  col_varchar?: string;
  col_char?: string;
  col_bytea?: Uint8Array;
  col_timestamp?: Date;
  col_timestamptz?: Date;
  col_date?: Date;
  col_interval?: string;
  col_uuid?: string;
  col_json?: unknown;
  col_jsonb?: { key: string; value: number };
  col_text_arr?: string[];
  col_int_arr?: number[];
  col_date_arr?: Date[];
  col_timestamptz_arr?: Date[];
  col_interval_arr?: string[];
  col_uuid_arr?: string[];
  col_bool_arr?: boolean[];
  created_at: Date;
  updated_at: Date;
};

type Defaults = "id" | "col_serial" | "col_bool" | "created_at" | "updated_at";
export type TypeTestCreate = Omit<TypeTest, Defaults> & Partial<Pick<TypeTest, Defaults>>;
export type TypeTestUpdate = Partial<Omit<TypeTest, "id">>;

const ARRAY_COLS = new Set(["col_text_arr", "col_int_arr", "col_date_arr", "col_timestamptz_arr", "col_interval_arr", "col_uuid_arr", "col_bool_arr"]);

export async function create(ctx: Context, data: TypeTestCreate): Promise<TypeTest> {
  const [row] = await ctx.sql`INSERT INTO public.type_test ${ctx.sql(prepareForSql(data as any, ARRAY_COLS))} RETURNING *`;
  return row as TypeTest;
}

export async function read(ctx: Context, id: string): Promise<TypeTest | null> {
  const rows = await ctx.sql`SELECT * FROM public.type_test WHERE id = ${id}`;
  return (rows[0] as TypeTest) ?? null;
}

export async function update(ctx: Context, id: string, data: TypeTestUpdate): Promise<TypeTest | null> {
  const rows = await ctx.sql`UPDATE public.type_test SET ${ctx.sql(prepareForSql(data as any, ARRAY_COLS))} WHERE id = ${id} RETURNING *`;
  return (rows[0] as TypeTest) ?? null;
}

export async function remove(ctx: Context, id: string): Promise<boolean> {
  const rows = await ctx.sql`DELETE FROM public.type_test WHERE id = ${id} RETURNING id`;
  return rows.length > 0;
}

export async function list(ctx: Context, opts: { limit?: number; offset?: number } = {}): Promise<TypeTest[]> {
  const { limit = 100, offset = 0 } = opts;
  return await ctx.sql`SELECT * FROM public.type_test ORDER BY id LIMIT ${limit} OFFSET ${offset}` as TypeTest[];
}
