// Auto-generated by codegen — DO NOT EDIT. Run: bun run db:codegen
import type { Context } from "../system.ts";

export type Users = {
  id: string;
  external_id?: string;
  user_name: string;
  name?: { givenName?: string; familyName?: string; middleName?: string; formatted?: string; honorificPrefix?: string; honorificSuffix?: string };
  display_name?: string;
  nick_name?: string;
  profile_url?: string;
  emails?: { value: string; type?: string; primary?: boolean }[];
  phone_numbers?: { value: string; type?: string }[];
  ims?: { value: string; type?: string }[];
  photos?: { value: string; type?: string }[];
  addresses?: { formatted?: string; streetAddress?: string; locality?: string; region?: string; postalCode?: string; country?: string; type?: string }[];
  title?: string;
  user_type?: string;
  roles?: { value: string; type?: string; primary?: boolean }[];
  entitlements?: { value: string; type?: string }[];
  preferred_language?: string;
  locale?: string;
  timezone?: string;
  active: boolean;
  password?: string;
  groups?: { value: string; display?: string; type?: string }[];
  x509_certificates?: { value: string; type?: string }[];
  created_at: Date;
  updated_at: Date;
  version?: string;
};

type Defaults = "id" | "active" | "created_at" | "updated_at";
export type UsersCreate = Omit<Users, Defaults> & Partial<Pick<Users, Defaults>>;
export type UsersUpdate = Partial<Omit<Users, "id">>;

export async function create(ctx: Context, data: UsersCreate): Promise<Users> {
  const [row] = await ctx.sql`INSERT INTO public.users ${ctx.sql(data)} RETURNING *`;
  return row as Users;
}

export async function read(ctx: Context, id: string): Promise<Users | null> {
  const rows = await ctx.sql`SELECT * FROM public.users WHERE id = ${id}`;
  return (rows[0] as Users) ?? null;
}

export async function update(ctx: Context, id: string, data: UsersUpdate): Promise<Users | null> {
  const rows = await ctx.sql`UPDATE public.users SET ${ctx.sql(data)} WHERE id = ${id} RETURNING *`;
  return (rows[0] as Users) ?? null;
}

export async function remove(ctx: Context, id: string): Promise<boolean> {
  const rows = await ctx.sql`DELETE FROM public.users WHERE id = ${id} RETURNING id`;
  return rows.length > 0;
}

export async function list(ctx: Context, opts: { limit?: number; offset?: number } = {}): Promise<Users[]> {
  const { limit = 100, offset = 0 } = opts;
  return await ctx.sql`SELECT * FROM public.users ORDER BY id LIMIT ${limit} OFFSET ${offset}` as Users[];
}
